### ISSUE TITLE
UI polishes and bug fixes [Epic]

### ISSUE THREAD

**Issue by frederickobrien** [guardian/recipes#59]
A centralised list of polishes and bug fixes:

- [ ] Make recipe ID the sole parameter of curation pages
- [ ] Display fractions as 1/2, 1/3 rather than 0.5, 0.333333, etc.
- [ ] Notes and discussion space / [Pinboard](https://github.com/guardian/pinboard) integration
- [ ] Tooltips and guidance for each form field
